import pandas as pd



def read_label_track(filepath, duration, delta=1e-8, unk='other'):
    """read Label Track file generated by Audicity

    :param filepath: audio filepath
    :type filepath: str
    :param duration: duration of the audio file
    :type duration: float
    :param delta: tolerence, defaults to 1e-8
    :type delta: float, optional
    :param unk: placeholder for not labeled intervals, defaults to 'other'
    :type unk: str, optional
    :return: a pandas DataFrame with `start`, `end`, `label` for each interval
    :rtype: pd.DataFrame
    """
    df = pd.read_csv(filepath, sep='\t', names=['start', 'end', 'label'])
    intervals = df.to_dict('records')

    full_intervals = []

    while intervals:
        interval = intervals.pop(0)
        
        if not full_intervals:
            if interval['start'] > 0.0:
                full_intervals.append({
                    'start': 0.0,
                    'end': interval['start'],
                    'label': unk,
                })
            full_intervals.append(interval)
        
        else:
            if interval['start'] - full_intervals[-1]['end'] > delta:
                full_intervals.append({
                    'start': full_intervals[-1]['end'],
                    'end': interval['start'],
                    'label': unk,
                })
            full_intervals.append(interval)

    if duration - full_intervals[-1]['end'] > delta:
        full_intervals.append({
            'start': full_intervals[-1]['end'],
            'end': duration,
            'label': unk,
        })

    df = pd.DataFrame(full_intervals)

    return df

