name: master
is_voice: true
use_redis: false

dl_endpoint:
  asr: ''
  tts: ''
  nlp_faq: ''

worker_endpoint:
  emsd: ''

state_storage:
  current_domain: null
  keyterm_pool: []

dialog_history:
  capacity: 10

