name: worker
is_voice: true
use_redis: false

dl_endpoint:
  asr: ''
  tts: ''
  nlp_faq: ''

worker_endpoint:
  emsd: ''

state_storage: null

dialog_history:
  capacity: 10

default_answers:
  clarifying_question: ""
  fallout_answer: ""
  